### PR TITLE
Revert "Allow assisted parameters of the same type"

### LINKED ISSUE #81: Request not to mandate same names for assisted parameters
Request not to mandate same names for assisted parameters. In my case, changing params to workerParameters fixed it but would be nice not to force same names.

InternalWorkerFactory.java:9: error: Factory method parameters do not match constructor @Assisted parameters.
    public abstract T create(@org.jetbrains.annotations.NotNull()
                      ^
  Missing:
   * androidx.work.WorkerParameters params
  Unknown:
   * androidx.work.WorkerParameters workerParameters

### PR DESCRIPTION
**Pull request by Egorand**
This is a manual revert of
12cfeac1fa03282b59f56522b2c2649da7066f27. Some files have
diverged too much making automated revert hard.

Closes #81. Closes #121. Closes #140.

### CODE REVIEW

**Comment by Egorand** [comment]
Also, please add me to contributors so I can kill my fork.

**Comment by markphetteplace** [comment]
I had no idea what I'm doing

**Comment by davidliu** [comment]
Is this simply going back to the previous implementation where qualifier annotations are required when providing multiple items of the same type (instead of matching by parameter name)?

**Comment by JakeWharton** [comment]
Yes. Incremental annotation processors mean you can never rely on parameters names being present. If you don't want to create an annotation, you can use `@Named("foo")`.

**Comment by Egorand** [comment]
@JakeWharton fine if I release 0.6.1 with this change?

**Comment by JakeWharton** [comment]
Waiting on #158 to land

**Comment by JakeWharton** [comment]
It is very much not a patch release, either, since it dramatically changes the behavior.

**Comment by Egorand** [comment]
Cool, will leave it to you then

**Pull request merged**
